-- Professional ticketing upgrade:
--   1) tickets.boarding_token — opaque boarding/validation token that the
--      barcode encodes (no passenger data). Unique + indexed for scan lookup.
--   2) ticket printing & boarding audit columns (who/when) so important
--      actions stay traceable per §24 audit requirements.
-- The ticket number format itself (TK-YYYY-NNNNNN) is generated by the
-- application under the existing UNIQUE constraint on tickets.number; no
-- schema change is needed for it.

ALTER TABLE "tickets"
  ADD COLUMN "boardingToken" TEXT,
  ADD COLUMN "printedAt" TIMESTAMP(3),
  ADD COLUMN "printedById" TEXT,
  ADD COLUMN "boardedAt" TIMESTAMP(3),
  ADD COLUMN "boardedById" TEXT;

CREATE UNIQUE INDEX "tickets_boardingToken_key" ON "tickets"("boardingToken");

-- Backfill: existing tickets receive a boarding token derived from their
-- existing QR uuid (already unique) so every ticket becomes scannable
-- immediately without re-issuing. qrCode stays the QR payload; the printed
-- barcode carries boardingToken. Both resolve to the same ticket.
UPDATE "tickets" SET "boardingToken" = "qrCode" WHERE "boardingToken" IS NULL;
